name: Site Pessoal

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Instalação do docker
        run: |
          sudo curl -fsSL https://get.docker.com/ | sh
          sudo apt-get update
          sudo apt-get install docker-ce
          sudo service docker start

      - name: Pull image from Docker Hub
        run: sudo docker pull ruanfonseca/meu-site:v1

      - name: Pull image from Docker Hub
        run: sudo docker pull ruanfonseca/back-site:v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Download Docker Compose file
        run: |
          curl -O https://raw.githubusercontent.com/Ruanfonseca/backhomepage/main/docker-compose.yml

      - name: Run Docker Compose
        run: sudo docker-compose up -d

