name: Site Pessoal

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17.0.9'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Login DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build Docker image
        run: docker build -t ruanfonseca/sitepessoalmail:latest .

      - name: Push Docker image
        run: docker push ruanfonseca/sitepessoalmail:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Fly CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          sudo curl -L https://fly.io/install.sh | sh
          sudo flyctl --version

      - name: Login to Fly.io
        run: flyctl auth login -e ${{secrets.FLY_USERNAME}} -p ${{secrets.FLY_PASSWORD}}

      - name: Deploy sitepessoalmail
        run: flyctl deploy -i ruanfonseca/sitepessoalmail:latest -a site

      - name: Deploy sitepessoalfront
        run: flyctl deploy -i ruanfonseca/sitepessoalfront:latest -a site
